version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  web:
    volumes:
      - ./.prettierrc:/usr/src/.prettierrc
      - ./.prettierignore:/usr/src/.prettierignore
  api:
    depends_on:
      - mongo
    volumes:
      - ./.prettierrc:/usr/src/.prettierrc
      - ./.prettierignore:/usr/src/.prettierignore

volumes:
  data-volume:
