export const JWT_LOGIN_EXPIRE_SECONDS = 604800;
export const JWT_PASSWORD_RESET_EXPIRE_SECONDS = 600;
export const JWT_USER_INVITE_EXPIRE_SECONDS = 604800;

export const WHITE_LABEL_TEMPLATE_NAME = 'whitelabel';
